on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

name: deploy updated script/data for badges
jobs:
  deploy_badges:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: deploy updated script/data for badges
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: cd badges && ./deploy https://top-github.eplus.dev
